name: Greet New Contributor

on:
  pull_request:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the user is a first-time contributor
        id: check
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |
            👋 Welcome @${{ github.actor }}!
            Thank you for your **first pull request** to this repository. 🙌  
            We’re happy to have you contributing! 🌟  
            Please make sure to follow our contributing guidelines.
